package www.kjfl.com.pingtai.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import www.kjfl.com.pingtai.bean.PingJia;
import www.kjfl.com.pingtai.bean.PingJiaExample;

@Mapper
public interface PingJiaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    long countByExample(PingJiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int deleteByExample(PingJiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int insert(PingJia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int insertSelective(PingJia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    List<PingJia> selectByExample(PingJiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    PingJia selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") PingJia record, @Param("example") PingJiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int updateByExample(@Param("record") PingJia record, @Param("example") PingJiaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int updateByPrimaryKeySelective(PingJia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    int updateByPrimaryKey(PingJia record);
}