package www.kjfl.com.pingtai.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import www.kjfl.com.pingtai.bean.QianDao;
import www.kjfl.com.pingtai.bean.QianDaoExample;

@Mapper
public interface QianDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    long countByExample(QianDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int deleteByExample(QianDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int deleteByPrimaryKey(String qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int insert(QianDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int insertSelective(QianDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    List<QianDao> selectByExample(QianDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    QianDao selectByPrimaryKey(String qid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") QianDao record, @Param("example") QianDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int updateByExample(@Param("record") QianDao record, @Param("example") QianDaoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int updateByPrimaryKeySelective(QianDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    int updateByPrimaryKey(QianDao record);
}