package www.kjfl.com.pingtai.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import www.kjfl.com.pingtai.bean.Useres;
import www.kjfl.com.pingtai.bean.UseresExample;

@Mapper
public interface UseresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    long countByExample(UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int deleteByExample(UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int insert(Useres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int insertSelective(Useres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    List<Useres> selectByExample(UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    Useres selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Useres record, @Param("example") UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int updateByExample(@Param("record") Useres record, @Param("example") UseresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int updateByPrimaryKeySelective(Useres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    int updateByPrimaryKey(Useres record);
}