package www.kjfl.com.pingtai.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HuiFuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public HuiFuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andHidIsNull() {
            addCriterion("hid is null");
            return (Criteria) this;
        }

        public Criteria andHidIsNotNull() {
            addCriterion("hid is not null");
            return (Criteria) this;
        }

        public Criteria andHidEqualTo(Integer value) {
            addCriterion("hid =", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotEqualTo(Integer value) {
            addCriterion("hid <>", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidGreaterThan(Integer value) {
            addCriterion("hid >", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidGreaterThanOrEqualTo(Integer value) {
            addCriterion("hid >=", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidLessThan(Integer value) {
            addCriterion("hid <", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidLessThanOrEqualTo(Integer value) {
            addCriterion("hid <=", value, "hid");
            return (Criteria) this;
        }

        public Criteria andHidIn(List<Integer> values) {
            addCriterion("hid in", values, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotIn(List<Integer> values) {
            addCriterion("hid not in", values, "hid");
            return (Criteria) this;
        }

        public Criteria andHidBetween(Integer value1, Integer value2) {
            addCriterion("hid between", value1, value2, "hid");
            return (Criteria) this;
        }

        public Criteria andHidNotBetween(Integer value1, Integer value2) {
            addCriterion("hid not between", value1, value2, "hid");
            return (Criteria) this;
        }

        public Criteria andHtidIsNull() {
            addCriterion("htid is null");
            return (Criteria) this;
        }

        public Criteria andHtidIsNotNull() {
            addCriterion("htid is not null");
            return (Criteria) this;
        }

        public Criteria andHtidEqualTo(Integer value) {
            addCriterion("htid =", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotEqualTo(Integer value) {
            addCriterion("htid <>", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidGreaterThan(Integer value) {
            addCriterion("htid >", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidGreaterThanOrEqualTo(Integer value) {
            addCriterion("htid >=", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidLessThan(Integer value) {
            addCriterion("htid <", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidLessThanOrEqualTo(Integer value) {
            addCriterion("htid <=", value, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidIn(List<Integer> values) {
            addCriterion("htid in", values, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotIn(List<Integer> values) {
            addCriterion("htid not in", values, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidBetween(Integer value1, Integer value2) {
            addCriterion("htid between", value1, value2, "htid");
            return (Criteria) this;
        }

        public Criteria andHtidNotBetween(Integer value1, Integer value2) {
            addCriterion("htid not between", value1, value2, "htid");
            return (Criteria) this;
        }

        public Criteria andHxuidIsNull() {
            addCriterion("hxuid is null");
            return (Criteria) this;
        }

        public Criteria andHxuidIsNotNull() {
            addCriterion("hxuid is not null");
            return (Criteria) this;
        }

        public Criteria andHxuidEqualTo(String value) {
            addCriterion("hxuid =", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidNotEqualTo(String value) {
            addCriterion("hxuid <>", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidGreaterThan(String value) {
            addCriterion("hxuid >", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidGreaterThanOrEqualTo(String value) {
            addCriterion("hxuid >=", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidLessThan(String value) {
            addCriterion("hxuid <", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidLessThanOrEqualTo(String value) {
            addCriterion("hxuid <=", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidLike(String value) {
            addCriterion("hxuid like", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidNotLike(String value) {
            addCriterion("hxuid not like", value, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidIn(List<String> values) {
            addCriterion("hxuid in", values, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidNotIn(List<String> values) {
            addCriterion("hxuid not in", values, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidBetween(String value1, String value2) {
            addCriterion("hxuid between", value1, value2, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHxuidNotBetween(String value1, String value2) {
            addCriterion("hxuid not between", value1, value2, "hxuid");
            return (Criteria) this;
        }

        public Criteria andHneirongIsNull() {
            addCriterion("hneirong is null");
            return (Criteria) this;
        }

        public Criteria andHneirongIsNotNull() {
            addCriterion("hneirong is not null");
            return (Criteria) this;
        }

        public Criteria andHneirongEqualTo(String value) {
            addCriterion("hneirong =", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongNotEqualTo(String value) {
            addCriterion("hneirong <>", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongGreaterThan(String value) {
            addCriterion("hneirong >", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongGreaterThanOrEqualTo(String value) {
            addCriterion("hneirong >=", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongLessThan(String value) {
            addCriterion("hneirong <", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongLessThanOrEqualTo(String value) {
            addCriterion("hneirong <=", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongLike(String value) {
            addCriterion("hneirong like", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongNotLike(String value) {
            addCriterion("hneirong not like", value, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongIn(List<String> values) {
            addCriterion("hneirong in", values, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongNotIn(List<String> values) {
            addCriterion("hneirong not in", values, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongBetween(String value1, String value2) {
            addCriterion("hneirong between", value1, value2, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHneirongNotBetween(String value1, String value2) {
            addCriterion("hneirong not between", value1, value2, "hneirong");
            return (Criteria) this;
        }

        public Criteria andHjuidIsNull() {
            addCriterion("hjuid is null");
            return (Criteria) this;
        }

        public Criteria andHjuidIsNotNull() {
            addCriterion("hjuid is not null");
            return (Criteria) this;
        }

        public Criteria andHjuidEqualTo(String value) {
            addCriterion("hjuid =", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidNotEqualTo(String value) {
            addCriterion("hjuid <>", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidGreaterThan(String value) {
            addCriterion("hjuid >", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidGreaterThanOrEqualTo(String value) {
            addCriterion("hjuid >=", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidLessThan(String value) {
            addCriterion("hjuid <", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidLessThanOrEqualTo(String value) {
            addCriterion("hjuid <=", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidLike(String value) {
            addCriterion("hjuid like", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidNotLike(String value) {
            addCriterion("hjuid not like", value, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidIn(List<String> values) {
            addCriterion("hjuid in", values, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidNotIn(List<String> values) {
            addCriterion("hjuid not in", values, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidBetween(String value1, String value2) {
            addCriterion("hjuid between", value1, value2, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHjuidNotBetween(String value1, String value2) {
            addCriterion("hjuid not between", value1, value2, "hjuid");
            return (Criteria) this;
        }

        public Criteria andHunameIsNull() {
            addCriterion("huname is null");
            return (Criteria) this;
        }

        public Criteria andHunameIsNotNull() {
            addCriterion("huname is not null");
            return (Criteria) this;
        }

        public Criteria andHunameEqualTo(String value) {
            addCriterion("huname =", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameNotEqualTo(String value) {
            addCriterion("huname <>", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameGreaterThan(String value) {
            addCriterion("huname >", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameGreaterThanOrEqualTo(String value) {
            addCriterion("huname >=", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameLessThan(String value) {
            addCriterion("huname <", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameLessThanOrEqualTo(String value) {
            addCriterion("huname <=", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameLike(String value) {
            addCriterion("huname like", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameNotLike(String value) {
            addCriterion("huname not like", value, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameIn(List<String> values) {
            addCriterion("huname in", values, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameNotIn(List<String> values) {
            addCriterion("huname not in", values, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameBetween(String value1, String value2) {
            addCriterion("huname between", value1, value2, "huname");
            return (Criteria) this;
        }

        public Criteria andHunameNotBetween(String value1, String value2) {
            addCriterion("huname not between", value1, value2, "huname");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiIsNull() {
            addCriterion("hbiaoshi is null");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiIsNotNull() {
            addCriterion("hbiaoshi is not null");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiEqualTo(Integer value) {
            addCriterion("hbiaoshi =", value, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiNotEqualTo(Integer value) {
            addCriterion("hbiaoshi <>", value, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiGreaterThan(Integer value) {
            addCriterion("hbiaoshi >", value, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiGreaterThanOrEqualTo(Integer value) {
            addCriterion("hbiaoshi >=", value, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiLessThan(Integer value) {
            addCriterion("hbiaoshi <", value, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiLessThanOrEqualTo(Integer value) {
            addCriterion("hbiaoshi <=", value, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiIn(List<Integer> values) {
            addCriterion("hbiaoshi in", values, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiNotIn(List<Integer> values) {
            addCriterion("hbiaoshi not in", values, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiBetween(Integer value1, Integer value2) {
            addCriterion("hbiaoshi between", value1, value2, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHbiaoshiNotBetween(Integer value1, Integer value2) {
            addCriterion("hbiaoshi not between", value1, value2, "hbiaoshi");
            return (Criteria) this;
        }

        public Criteria andHpingjiaIsNull() {
            addCriterion("hpingjia is null");
            return (Criteria) this;
        }

        public Criteria andHpingjiaIsNotNull() {
            addCriterion("hpingjia is not null");
            return (Criteria) this;
        }

        public Criteria andHpingjiaEqualTo(Integer value) {
            addCriterion("hpingjia =", value, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaNotEqualTo(Integer value) {
            addCriterion("hpingjia <>", value, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaGreaterThan(Integer value) {
            addCriterion("hpingjia >", value, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpingjia >=", value, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaLessThan(Integer value) {
            addCriterion("hpingjia <", value, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaLessThanOrEqualTo(Integer value) {
            addCriterion("hpingjia <=", value, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaIn(List<Integer> values) {
            addCriterion("hpingjia in", values, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaNotIn(List<Integer> values) {
            addCriterion("hpingjia not in", values, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaBetween(Integer value1, Integer value2) {
            addCriterion("hpingjia between", value1, value2, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHpingjiaNotBetween(Integer value1, Integer value2) {
            addCriterion("hpingjia not between", value1, value2, "hpingjia");
            return (Criteria) this;
        }

        public Criteria andHtimeIsNull() {
            addCriterion("htime is null");
            return (Criteria) this;
        }

        public Criteria andHtimeIsNotNull() {
            addCriterion("htime is not null");
            return (Criteria) this;
        }

        public Criteria andHtimeEqualTo(Date value) {
            addCriterionForJDBCDate("htime =", value, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("htime <>", value, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("htime >", value, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("htime >=", value, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeLessThan(Date value) {
            addCriterionForJDBCDate("htime <", value, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("htime <=", value, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeIn(List<Date> values) {
            addCriterionForJDBCDate("htime in", values, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("htime not in", values, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("htime between", value1, value2, "htime");
            return (Criteria) this;
        }

        public Criteria andHtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("htime not between", value1, value2, "htime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table huifu
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 03 19:34:18 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}