package www.kjfl.com.pingtai.bean;

import java.io.Serializable;
import java.util.Date;

public class HuiFu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.hid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.htid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer htid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.hxuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String hxuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.hneirong
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String hneirong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.hjuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String hjuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.huname
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String huname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.hbiaoshi
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer hbiaoshi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.hpingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer hpingjia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huifu.htime
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Date htime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.hid
     *
     * @return the value of huifu.hid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.hid
     *
     * @param hid the value for huifu.hid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.htid
     *
     * @return the value of huifu.htid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getHtid() {
        return htid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.htid
     *
     * @param htid the value for huifu.htid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHtid(Integer htid) {
        this.htid = htid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.hxuid
     *
     * @return the value of huifu.hxuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getHxuid() {
        return hxuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.hxuid
     *
     * @param hxuid the value for huifu.hxuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHxuid(String hxuid) {
        this.hxuid = hxuid == null ? null : hxuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.hneirong
     *
     * @return the value of huifu.hneirong
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getHneirong() {
        return hneirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.hneirong
     *
     * @param hneirong the value for huifu.hneirong
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHneirong(String hneirong) {
        this.hneirong = hneirong == null ? null : hneirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.hjuid
     *
     * @return the value of huifu.hjuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getHjuid() {
        return hjuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.hjuid
     *
     * @param hjuid the value for huifu.hjuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHjuid(String hjuid) {
        this.hjuid = hjuid == null ? null : hjuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.huname
     *
     * @return the value of huifu.huname
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getHuname() {
        return huname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.huname
     *
     * @param huname the value for huifu.huname
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHuname(String huname) {
        this.huname = huname == null ? null : huname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.hbiaoshi
     *
     * @return the value of huifu.hbiaoshi
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getHbiaoshi() {
        return hbiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.hbiaoshi
     *
     * @param hbiaoshi the value for huifu.hbiaoshi
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHbiaoshi(Integer hbiaoshi) {
        this.hbiaoshi = hbiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.hpingjia
     *
     * @return the value of huifu.hpingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getHpingjia() {
        return hpingjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.hpingjia
     *
     * @param hpingjia the value for huifu.hpingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHpingjia(Integer hpingjia) {
        this.hpingjia = hpingjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huifu.htime
     *
     * @return the value of huifu.htime
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Date getHtime() {
        return htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huifu.htime
     *
     * @param htime the value for huifu.htime
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setHtime(Date htime) {
        this.htime = htime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table huifu
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hid=").append(hid);
        sb.append(", htid=").append(htid);
        sb.append(", hxuid=").append(hxuid);
        sb.append(", hneirong=").append(hneirong);
        sb.append(", hjuid=").append(hjuid);
        sb.append(", huname=").append(huname);
        sb.append(", hbiaoshi=").append(hbiaoshi);
        sb.append(", hpingjia=").append(hpingjia);
        sb.append(", htime=").append(htime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}