package www.kjfl.com.pingtai.bean;

import java.io.Serializable;

public class JingLi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingli.fid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingli.fname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jingli.fsj
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private String fsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jingli
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingli.fid
     *
     * @return the value of jingli.fid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingli.fid
     *
     * @param fid the value for jingli.fid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingli.fname
     *
     * @return the value of jingli.fname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingli.fname
     *
     * @param fname the value for jingli.fname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jingli.fsj
     *
     * @return the value of jingli.fsj
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public String getFsj() {
        return fsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jingli.fsj
     *
     * @param fsj the value for jingli.fsj
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setFsj(String fsj) {
        this.fsj = fsj == null ? null : fsj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jingli
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fid=").append(fid);
        sb.append(", fname=").append(fname);
        sb.append(", fsj=").append(fsj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}