package www.kjfl.com.pingtai.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PingJiaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public PingJiaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Integer value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Integer value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Integer value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Integer value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Integer value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Integer value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Integer> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Integer> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Integer value1, Integer value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Integer value1, Integer value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPhidIsNull() {
            addCriterion("phid is null");
            return (Criteria) this;
        }

        public Criteria andPhidIsNotNull() {
            addCriterion("phid is not null");
            return (Criteria) this;
        }

        public Criteria andPhidEqualTo(Integer value) {
            addCriterion("phid =", value, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidNotEqualTo(Integer value) {
            addCriterion("phid <>", value, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidGreaterThan(Integer value) {
            addCriterion("phid >", value, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidGreaterThanOrEqualTo(Integer value) {
            addCriterion("phid >=", value, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidLessThan(Integer value) {
            addCriterion("phid <", value, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidLessThanOrEqualTo(Integer value) {
            addCriterion("phid <=", value, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidIn(List<Integer> values) {
            addCriterion("phid in", values, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidNotIn(List<Integer> values) {
            addCriterion("phid not in", values, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidBetween(Integer value1, Integer value2) {
            addCriterion("phid between", value1, value2, "phid");
            return (Criteria) this;
        }

        public Criteria andPhidNotBetween(Integer value1, Integer value2) {
            addCriterion("phid not between", value1, value2, "phid");
            return (Criteria) this;
        }

        public Criteria andPxuidIsNull() {
            addCriterion("pxuid is null");
            return (Criteria) this;
        }

        public Criteria andPxuidIsNotNull() {
            addCriterion("pxuid is not null");
            return (Criteria) this;
        }

        public Criteria andPxuidEqualTo(String value) {
            addCriterion("pxuid =", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidNotEqualTo(String value) {
            addCriterion("pxuid <>", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidGreaterThan(String value) {
            addCriterion("pxuid >", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidGreaterThanOrEqualTo(String value) {
            addCriterion("pxuid >=", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidLessThan(String value) {
            addCriterion("pxuid <", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidLessThanOrEqualTo(String value) {
            addCriterion("pxuid <=", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidLike(String value) {
            addCriterion("pxuid like", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidNotLike(String value) {
            addCriterion("pxuid not like", value, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidIn(List<String> values) {
            addCriterion("pxuid in", values, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidNotIn(List<String> values) {
            addCriterion("pxuid not in", values, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidBetween(String value1, String value2) {
            addCriterion("pxuid between", value1, value2, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPxuidNotBetween(String value1, String value2) {
            addCriterion("pxuid not between", value1, value2, "pxuid");
            return (Criteria) this;
        }

        public Criteria andPjuidIsNull() {
            addCriterion("pjuid is null");
            return (Criteria) this;
        }

        public Criteria andPjuidIsNotNull() {
            addCriterion("pjuid is not null");
            return (Criteria) this;
        }

        public Criteria andPjuidEqualTo(String value) {
            addCriterion("pjuid =", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidNotEqualTo(String value) {
            addCriterion("pjuid <>", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidGreaterThan(String value) {
            addCriterion("pjuid >", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidGreaterThanOrEqualTo(String value) {
            addCriterion("pjuid >=", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidLessThan(String value) {
            addCriterion("pjuid <", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidLessThanOrEqualTo(String value) {
            addCriterion("pjuid <=", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidLike(String value) {
            addCriterion("pjuid like", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidNotLike(String value) {
            addCriterion("pjuid not like", value, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidIn(List<String> values) {
            addCriterion("pjuid in", values, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidNotIn(List<String> values) {
            addCriterion("pjuid not in", values, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidBetween(String value1, String value2) {
            addCriterion("pjuid between", value1, value2, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPjuidNotBetween(String value1, String value2) {
            addCriterion("pjuid not between", value1, value2, "pjuid");
            return (Criteria) this;
        }

        public Criteria andPneirongIsNull() {
            addCriterion("pneirong is null");
            return (Criteria) this;
        }

        public Criteria andPneirongIsNotNull() {
            addCriterion("pneirong is not null");
            return (Criteria) this;
        }

        public Criteria andPneirongEqualTo(String value) {
            addCriterion("pneirong =", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongNotEqualTo(String value) {
            addCriterion("pneirong <>", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongGreaterThan(String value) {
            addCriterion("pneirong >", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongGreaterThanOrEqualTo(String value) {
            addCriterion("pneirong >=", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongLessThan(String value) {
            addCriterion("pneirong <", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongLessThanOrEqualTo(String value) {
            addCriterion("pneirong <=", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongLike(String value) {
            addCriterion("pneirong like", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongNotLike(String value) {
            addCriterion("pneirong not like", value, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongIn(List<String> values) {
            addCriterion("pneirong in", values, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongNotIn(List<String> values) {
            addCriterion("pneirong not in", values, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongBetween(String value1, String value2) {
            addCriterion("pneirong between", value1, value2, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPneirongNotBetween(String value1, String value2) {
            addCriterion("pneirong not between", value1, value2, "pneirong");
            return (Criteria) this;
        }

        public Criteria andPtimeIsNull() {
            addCriterion("ptime is null");
            return (Criteria) this;
        }

        public Criteria andPtimeIsNotNull() {
            addCriterion("ptime is not null");
            return (Criteria) this;
        }

        public Criteria andPtimeEqualTo(Date value) {
            addCriterionForJDBCDate("ptime =", value, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("ptime <>", value, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("ptime >", value, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ptime >=", value, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeLessThan(Date value) {
            addCriterionForJDBCDate("ptime <", value, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ptime <=", value, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeIn(List<Date> values) {
            addCriterionForJDBCDate("ptime in", values, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("ptime not in", values, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ptime between", value1, value2, "ptime");
            return (Criteria) this;
        }

        public Criteria andPtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ptime not between", value1, value2, "ptime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pingjia
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 03 19:34:18 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pingjia
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}