package www.kjfl.com.pingtai.bean;

import java.io.Serializable;
import java.util.Date;

public class QianDao implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandao.qid
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    private String qid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandao.qtime
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    private Date qtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandao.qwcs
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    private Integer qwcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qiandao.qjintian
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    private Integer qjintian;
    private String uid;
    private String uname;
    private Integer shenhe;
    private Integer ubiaoshi;

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    public Integer getShenhe() {
        return shenhe;
    }

    public void setShenhe(Integer shenhe) {
        this.shenhe = shenhe;
    }

    public Integer getUbiaoshi() {
        return ubiaoshi;
    }

    public void setUbiaoshi(Integer ubiaoshi) {
        this.ubiaoshi = ubiaoshi;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandao.qid
     *
     * @return the value of qiandao.qid
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public String getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandao.qid
     *
     * @param qid the value for qiandao.qid
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public void setQid(String qid) {
        this.qid = qid == null ? null : qid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandao.qtime
     *
     * @return the value of qiandao.qtime
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public Date getQtime() {
        return qtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandao.qtime
     *
     * @param qtime the value for qiandao.qtime
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public void setQtime(Date qtime) {
        this.qtime = qtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandao.qwcs
     *
     * @return the value of qiandao.qwcs
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public Integer getQwcs() {
        return qwcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandao.qwcs
     *
     * @param qwcs the value for qiandao.qwcs
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public void setQwcs(Integer qwcs) {
        this.qwcs = qwcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qiandao.qjintian
     *
     * @return the value of qiandao.qjintian
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public Integer getQjintian() {
        return qjintian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qiandao.qjintian
     *
     * @param qjintian the value for qiandao.qjintian
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    public void setQjintian(Integer qjintian) {
        this.qjintian = qjintian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qiandao
     *
     * @mbg.generated Fri Jan 04 09:03:03 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", qid=").append(qid);
        sb.append(", qtime=").append(qtime);
        sb.append(", qwcs=").append(qwcs);
        sb.append(", qjintian=").append(qjintian);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}