package www.kjfl.com.pingtai.bean;

import java.io.Serializable;
import java.util.Date;

public class TiWen implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.tid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.tuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String tuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.tbiaoti
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String tbiaoti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.tneirong
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private String tneirong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.tdengji
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer tdengji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.tjiejue
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Integer tjiejue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tiwen.ttime
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private Date ttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tiwen
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.tid
     *
     * @return the value of tiwen.tid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.tid
     *
     * @param tid the value for tiwen.tid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.tuid
     *
     * @return the value of tiwen.tuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getTuid() {
        return tuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.tuid
     *
     * @param tuid the value for tiwen.tuid
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTuid(String tuid) {
        this.tuid = tuid == null ? null : tuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.tbiaoti
     *
     * @return the value of tiwen.tbiaoti
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getTbiaoti() {
        return tbiaoti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.tbiaoti
     *
     * @param tbiaoti the value for tiwen.tbiaoti
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTbiaoti(String tbiaoti) {
        this.tbiaoti = tbiaoti == null ? null : tbiaoti.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.tneirong
     *
     * @return the value of tiwen.tneirong
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public String getTneirong() {
        return tneirong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.tneirong
     *
     * @param tneirong the value for tiwen.tneirong
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTneirong(String tneirong) {
        this.tneirong = tneirong == null ? null : tneirong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.tdengji
     *
     * @return the value of tiwen.tdengji
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getTdengji() {
        return tdengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.tdengji
     *
     * @param tdengji the value for tiwen.tdengji
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTdengji(Integer tdengji) {
        this.tdengji = tdengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.tjiejue
     *
     * @return the value of tiwen.tjiejue
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Integer getTjiejue() {
        return tjiejue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.tjiejue
     *
     * @param tjiejue the value for tiwen.tjiejue
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTjiejue(Integer tjiejue) {
        this.tjiejue = tjiejue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tiwen.ttime
     *
     * @return the value of tiwen.ttime
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public Date getTtime() {
        return ttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tiwen.ttime
     *
     * @param ttime the value for tiwen.ttime
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    public void setTtime(Date ttime) {
        this.ttime = ttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tiwen
     *
     * @mbg.generated Thu Jan 03 19:34:18 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tid=").append(tid);
        sb.append(", tuid=").append(tuid);
        sb.append(", tbiaoti=").append(tbiaoti);
        sb.append(", tneirong=").append(tneirong);
        sb.append(", tdengji=").append(tdengji);
        sb.append(", tjiejue=").append(tjiejue);
        sb.append(", ttime=").append(ttime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}