package www.kjfl.com.pingtai.bean;

import java.io.Serializable;

public class Useres implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ubiaoshi
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer ubiaoshi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.umima
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private String umima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shenhe
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer shenhe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.yid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer yid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.jf
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer jf;

    private String fname;
    private String yname;

    public String getFname() {
        return fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getYname() {
        return yname;
    }

    public void setYname(String yname) {
        this.yname = yname;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ubiaoshi
     *
     * @return the value of user.ubiaoshi
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getUbiaoshi() {
        return ubiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ubiaoshi
     *
     * @param ubiaoshi the value for user.ubiaoshi
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setUbiaoshi(Integer ubiaoshi) {
        this.ubiaoshi = ubiaoshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.umima
     *
     * @return the value of user.umima
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public String getUmima() {
        return umima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.umima
     *
     * @param umima the value for user.umima
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setUmima(String umima) {
        this.umima = umima == null ? null : umima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shenhe
     *
     * @return the value of user.shenhe
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getShenhe() {
        return shenhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shenhe
     *
     * @param shenhe the value for user.shenhe
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setShenhe(Integer shenhe) {
        this.shenhe = shenhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fid
     *
     * @return the value of user.fid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fid
     *
     * @param fid the value for user.fid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.yid
     *
     * @return the value of user.yid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getYid() {
        return yid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.yid
     *
     * @param yid the value for user.yid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setYid(Integer yid) {
        this.yid = yid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.jf
     *
     * @return the value of user.jf
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getJf() {
        return jf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.jf
     *
     * @param jf the value for user.jf
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setJf(Integer jf) {
        this.jf = jf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uid=").append(uid);
        sb.append(", uname=").append(uname);
        sb.append(", ubiaoshi=").append(ubiaoshi);
        sb.append(", umima=").append(umima);
        sb.append(", shenhe=").append(shenhe);
        sb.append(", fid=").append(fid);
        sb.append(", yid=").append(yid);
        sb.append(", jf=").append(jf);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}