package www.kjfl.com.pingtai.bean;

import java.io.Serializable;

public class XueYuan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueyuan.yid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private Integer yid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xueyuan.yname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private String yname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xueyuan
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueyuan.yid
     *
     * @return the value of xueyuan.yid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public Integer getYid() {
        return yid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueyuan.yid
     *
     * @param yid the value for xueyuan.yid
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setYid(Integer yid) {
        this.yid = yid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xueyuan.yname
     *
     * @return the value of xueyuan.yname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public String getYname() {
        return yname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xueyuan.yname
     *
     * @param yname the value for xueyuan.yname
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    public void setYname(String yname) {
        this.yname = yname == null ? null : yname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xueyuan
     *
     * @mbg.generated Mon Dec 31 14:29:51 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", yid=").append(yid);
        sb.append(", yname=").append(yname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}